### ISSUE TITLE
Explicit checkpointing on WriteAheadLog

### ISSUE THREAD

**Issue by blakesmith** [khonsulabs/okaywal#10]
Hi there!

I'm playing around with okaywal, and am curious about the ability to intentionally force a checkpoint operation on the WAL.

My usecase: I want to be able to explicitly 'drain' a storage node, which would force all of its log entries to be checkpointed, before decommissioning the node.

I couldn't find any explicit way to do this from reading the source, but please let me know if I'm missing something. Otherwise, I'd be happy to submit a PR if you think it's a good idea.

Thanks, and thanks for open sourcing okaywal!

**Comment by ecton** [comment]
This sounds like a great addition, and I would be happy to accept a PR with it. If you have any questions during implementation, I'm happy to help!

**Comment by ecton** [comment]
I've released v0.3.0 with your PR merged. Sorry for the delay in merging and lack of response in the meantime. I thought I had replied, but apparently I had gotten distracted before finishing my previous reply. The main source of the delay was me trying to figure out if I wanted to try to publish the new crate `main` depends on. 

In the end, I just cherry-picked your change on top of the current release so that you could have it sooner rather than later. Thank you for your contribution!
